logging:
  config: file:/opt/aplicaciones/linsce/batch/adquirente/outgoing/carso/log/logback.xml
log4j:
  logger:
    org:
      springframework:
        jdbc:
          core: TRACE
nombre-proceso: bo-mx-disputes-batch-cmp-carso.yml
spring:
  sql:
    datasource:
      jdbc-url: jdbc:sqlserver://etl-sqls-dev.c11fwywckveg.us-east-1.rds.amazonaws.com:1433;databaseName=Linsce_Adq_br;encrypt=true;trustServerCertificate=true
      username: admin
      password: 9f4dcRPkqhY8
      data-source-properties:
        config-table: dbo.c_origen
        log-table: dbo.LogPackage
        cmp-table: dbo.oucmpcarso
        petition-table: dbo.d_peticion
        negocio-table: dbo.c_negocio
        conversion-emisores-table: dbo.cConversionEmisores
        dias-festivos: dbo.c_dias_festivos
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      environment: server
    datasource-lots:
      jdbc-url: jdbc:sqlserver://etl-sqls-dev.c11fwywckveg.us-east-1.rds.amazonaws.com:1433;databaseName=lotes_br;encrypt=true;trustServerCertificate=true
      username: admin
      password: 9f4dcRPkqhY8
      data-source-properties:
        lots-table: dbo.lotes_br
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      environment: server
    batch:
      jdbc:
        initialize-schema: never
authentication:
  method: basic
  cyberark-url: http://localhost:8080/cyberark/
  folder: 1231
  object: 4111
  reason: 1212
  app-id: 6712
  safe: 00191
authentication-lots:
  method: basic
  cyberark-url: http://localhost:8080/cyberark/
  folder: 1231
  object: 4111
  reason: 1212
  app-id: 6712
  safe: 00191
cmp:
  file-name: cmp
  output-path: /app/eBind/batch/bo-mx-disputes-batch-cmp-carso/resultado/
c-adq-numero: 12
c-sta-clave: D,005,006,007,008,009,010,011,10
d-pet-tip-tra: 1
c-neg-grupo: 13,210,05,1758,4006
lotes-id-status: A   