logging:
  config: file:/opt/aplicaciones/linsce/batch/adquirente/incoming/banamex/bo-mx-banamex-commerce-dlls-update-batch-main/log/logback.xml
log4j:
  logger:
    org:
      springframework:
        jdbc:
          core: TRACE
nombre-proceso: bo-mx-banamex-commerce-dlls-update-batch-main
spring:
  sql:
    datasource-target:
      jdbc-url: jdbc:sqlserver://etl-sqls-dev.c11fwywckveg.us-east-1.rds.amazonaws.com:1433;databaseName=Linsce_Adq_br;encrypt=true;trustServerCertificate=true
      username: admin
      password: 9f4dcRPkqhY8
      data-source-properties:
        config-table: dbo.c_origen
        log-table: dbo.LogPackage
        comercio-table: dbo.comer_bx
        negocio-table: dbo.c_negocio
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      environment: server
    batch:
      jdbc:
        initialize-schema: never
authentication-target:
  method: basic
  cyberark-url: http://localhost:8080/cyberark/
  folder: 1231
  object: 4111
  reason: 1212
  app-id: 6712
  safe: 00191
