logging:
  config: file:/opt/aplicaciones/linsce/batch/emisor/incoming/me/bo-mx-issuer-disputes-etl-upload/log/logback.xml
log4j:
  logger:
    org:
      springframework:
        jdbc:
          core: TRACE
nombre-proceso: bo-mx-issuer-disputes-etl-upload
spring:
  datasource:
    jdbc-url: jdbc:sqlserver://localhost:1434;databaseName=linsce_emisor;encrypt=true;trustServerCertificate=true
    #jdbc-url: jdbc:sqlserver://etl-sqls-dev.c11fwywckveg.us-east-1.rds.amazonaws.com:1433;databaseName=linsce_emisor;encrypt=true;trustServerCertificate=true
    username: zAplCont01
    password: #0ct3Z8m4X0coy0tz1n
    data-source-properties:
      rewriteBatchedStatements: true
      batchSize: 100
    config-table: catalogos.cArchivosIncoming
    log-table: dbo.LogPackage
    clarification-table: dbo.dAclaracion
    file-upload-table: dbo.ICargaArchivoIncoming
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    machine-name: maquinaIvana
  encripted-psw: false
  decrypt-key: 12341234
  environment: server
authentication:
  method: basic
  cyberark-url: http://localhost:8080/cyberark/
  folder: 1231
  object: 4111
  reason: 1212
  app-id: 6712
  safe: 00191